//! Golden fixtures shared by the parity and end-to-end tests.
//!
//! GENERATED by `scripts/gen_fixtures.mjs` — do not edit by hand. Values come
//! from the Molpha EVM golden vectors
//! (`molpha-core-contracts/test/fixtures/{fixture,attestation}.json`), which the
//! Solidity and Rust suites assert against too. Regenerating is how a
//! cross-VM change reaches this file; editing a constant to make a test pass
//! would hide exactly the drift these fixtures exist to catch.

use verifier::byte_utils::append_u256_be;

// ---- 12-node round (fixture.json) ----
pub const REG_VERSION: u32 = 12;
pub const SIGS_REQUIRED: u8 = 5;
pub const REDUNDANCY_BUFFER: u32 = 2;
pub const NODE_COUNT: u32 = 12;
pub const TIMESTAMP: u64 = 1700034927000;
pub const SIGNERS_BITMAP: u256 = 2032;
pub const COMMITMENT: felt252 = 0xec61e25b5a06f0a3f9048356b23e98cf775974b9;

pub fn SOURCE_ID() -> u256 {
    u256 { high: 0x93893838ba3cf2a46fc061b4c3acfba3, low: 0x435fa61b0c29017fe78280146255b604 }
}
pub fn VALUE() -> u256 {
    u256 { high: 0xc6d8f1c0fdb8997313cbc4bc43b46af7, low: 0x8589ba4bb9036707097db8b33879d6c6 }
}
pub fn SIGNATURE() -> u256 {
    u256 { high: 0x956e684ea6710c54bb7d5b0b3256e1c2, low: 0xd1e77cc84607ad575b5f95fdd210aac6 }
}
pub fn MESSAGE() -> u256 {
    u256 { high: 0x58489d3ded5f129c6fca09a174ff0dcf, low: 0x35c58f70c560e2d5ce538ef10c3bbb3e }
}
pub fn SELECTION_SEED() -> u256 {
    u256 { high: 0x3681e4e646690a473cd3594c9edca11e, low: 0xe038363ee745177d9314388892f05a93 }
}
pub fn AGG_X() -> u256 {
    u256 { high: 0xd210d01d70b5367d3e6b0bc245fd3592, low: 0xbf8ef9cb9b8cca64f932fb541831f34f }
}
pub fn AGG_Y() -> u256 {
    u256 { high: 0x0eed148ba2ba693698f256d576a2b3aa, low: 0x0889480ca4365c792252b34235132194 }
}

/// (prefix, x, secret_key) for each of the 12 fixture nodes, in index order.
pub fn fixture_nodes() -> Array<(u8, u256, u256)> {
    array![
        (
            3,
            u256 { high: 0x1531a401a017486c6fbd1e2819256e75, low: 0x9e5f2ec34e250bbbe0f7819f1806537b },
            u256 { high: 0x8757516e2dda2fb8b39f5e68b1631b93, low: 0xff304f24cd78009ed888b701f7f2adcb },
        ),
        (
            2,
            u256 { high: 0x2c04478953f5d4926f13e38f08282038, low: 0x5d3d3cfc43c29790bea9e253ca9438f4 },
            u256 { high: 0xcced3bbe6fe6554a801bbd991120876a, low: 0x724d4b5a0d354be25e1c0af5f19b5a43 },
        ),
        (
            3,
            u256 { high: 0x35859fed27c867c1c37baeb4c14c255a, low: 0xe4ab77165869905bddd4b1de7b36b62a },
            u256 { high: 0x3e4462265332e4355d3118f91e40547a, low: 0xa695d357a1cb9300dcd3d8366a2cfb11 },
        ),
        (
            2,
            u256 { high: 0x7b09304a77a2304029269c14c54a7d20, low: 0x86e6e38fa682903c038db8cb8ce5591f },
            u256 { high: 0xb4ceb4788a74f290fe6c65cf875b3aa5, low: 0x75708cba7c676b1a0c4ed5a69506eeb2 },
        ),
        (
            3,
            u256 { high: 0x45abc5b8bb51f8af1cb60211403277bf, low: 0x67e5177d918c5f38cf4250866a72c733 },
            u256 { high: 0x5cfa26e03f654991f7cb35a7d77b7d34, low: 0x7decf5fc57c0390cdfa7461e563d5137 },
        ),
        (
            3,
            u256 { high: 0x8b5521f1713f0bcef501aad3f2456aeb, low: 0xf162e6ae7f51adf0dc11f24cbbf32006 },
            u256 { high: 0x497197c4836e9f26d4b97e12a0dd08f6, low: 0x3e0bef49fca62a7448a17f39fef16ee7 },
        ),
        (
            3,
            u256 { high: 0xde1de25e2d769fe44e06980df8efcfdd, low: 0x6001ccd2919d2c5bcfc34567113bcc8e },
            u256 { high: 0x78c18971a74058259088fd8796e3cc20, low: 0x83c1fbacdbc269b600912e26e1094fb1 },
        ),
        (
            3,
            u256 { high: 0x88c63ec5de23e60f0128a3261578e9c6, low: 0xd2aeb56c5a162407363502201b89c0ee },
            u256 { high: 0xb9b99ff382e83d9759936b073509cbbd, low: 0xc27a51939a087049e6306de8cd23435a },
        ),
        (
            2,
            u256 { high: 0xc95bf4021c3c88ac50d1c0d0683df2b0, low: 0x0f19847d5712770c1cd7e22f3906284e },
            u256 { high: 0x345bc1c1a9416a377d835bbcffb677cc, low: 0x39cffadbbebb12898425f1d7deca1c16 },
        ),
        (
            2,
            u256 { high: 0x0c4922d73fad4f527e55b3d963e52f25, low: 0xd6920c54900077aef640fc8d95b048df },
            u256 { high: 0xd2d173087794a192d1c805505640bab5, low: 0xbbe4781cc202c1028ff51fffe24584d9 },
        ),
        (
            3,
            u256 { high: 0xdb69134e1f0e332cff00eb41e0fb8971, low: 0x42ba43dc9bedc5b18f18637705a4d6a4 },
            u256 { high: 0xb4413a5077269bc45b52b12e8824b1ef, low: 0xd8491e6862dd30880bdb400e06c9846f },
        ),
        (
            2,
            u256 { high: 0xb83c92c8d70a743e7d098be2257cc768, low: 0x9322d6979b8eb86710db53a35739868e },
            u256 { high: 0xa65297439e5738fe5ecf5cb1d0cfa450, low: 0xde6577e0ddd773e69936d973a5cdc6f0 },
        ),
    ]
}

/// Builds a 33-byte compressed pubkey ByteArray from prefix + x.
pub fn compressed(prefix: u8, x: u256) -> ByteArray {
    let mut b: ByteArray = "";
    b.append_byte(prefix);
    append_u256_be(ref b, x);
    b
}

// ---- end-to-end cases (attestation.json), same key set ----
//
// Each carries the code the EVM verifier returns, so the Cairo port is checked
// on the `(success, code)` pair rather than just acceptance.

/// `kindA-int256` (kind A): expects (true, 0).
pub const CASE1_REG_VERSION: u32 = 12;
pub const CASE1_SIGS_REQUIRED: u8 = 5;
pub const CASE1_TIMESTAMP: u64 = 1700000000000;
pub const CASE1_SIGNERS_BITMAP: u256 = 339;
pub const CASE1_COMMITMENT: felt252 = 0x2d91b53b7dae92b3731d690efc315f2695bb0975;
pub const CASE1_EXPECTED_OK: bool = true;
pub const CASE1_EXPECTED_CODE: u8 = 0;
pub fn CASE1_SOURCE_ID() -> u256 {
    u256 { high: 0xa6729f7c91f13795a38aa67f4bc816fa, low: 0xe5bef9ffbeb4319c69a9242f2e68cdbc }
}
pub fn CASE1_VALUE() -> u256 {
    u256 { high: 0xffffffffffffffffffffffffffffffff, low: 0xfffffffffffffffffffffffffffffb2e }
}
pub fn CASE1_SIGNATURE() -> u256 {
    u256 { high: 0x8d0597c6d418a8c6397ad832cda1ed2d, low: 0x1d55e2777943bb5ca83160ba9118a4fd }
}
pub fn CASE1_MESSAGE() -> u256 {
    u256 { high: 0x1f081c05ef4dfa658a55dd6e80cd70c3, low: 0x4710fce23b771a3422ac079aa09c8da8 }
}

/// `kindB-tuple` (kind B): expects (true, 0).
pub const CASE2_REG_VERSION: u32 = 12;
pub const CASE2_SIGS_REQUIRED: u8 = 5;
pub const CASE2_TIMESTAMP: u64 = 1700000000000;
pub const CASE2_SIGNERS_BITMAP: u256 = 339;
pub const CASE2_COMMITMENT: felt252 = 0x3b7d9f9859a5aaac41557a21c2b610dbf785207f;
pub const CASE2_EXPECTED_OK: bool = true;
pub const CASE2_EXPECTED_CODE: u8 = 0;
pub fn CASE2_SOURCE_ID() -> u256 {
    u256 { high: 0xa6729f7c91f13795a38aa67f4bc816fa, low: 0xe5bef9ffbeb4319c69a9242f2e68cdbc }
}
pub fn CASE2_VALUE() -> u256 {
    u256 { high: 0x47869257dae795e85b30cb6a0ac7f82f, low: 0xe977ec5ced28d96a70f3fe2cb514ff1a }
}
pub fn CASE2_SIGNATURE() -> u256 {
    u256 { high: 0xaa61b446b25fbd7a0c35f58394df91c9, low: 0x709ff7065612986602b895dc929d267c }
}
pub fn CASE2_MESSAGE() -> u256 {
    u256 { high: 0x73e42f102997909d3a191cfbf210efba, low: 0x1564f263847b527fe8472784ff070965 }
}
